@apiURL = http://localhost:8080/notes

GET {{apiURL}}

###

POST {{apiURL}}
Content-Type: application/json

{  
    "author_id": 3,
    "text": "Köp ost!" 
}

###

DELETE {{apiURL}}/5

@apiURL = http://localhost:8070/notes

###
PUT {{apiURL}}/1
Content-Type: application/json

{ "text": "köp bröd"}
