@apiURL = http://localhost:8060/notes

GET {{apiURL}}

###
GET {{apiURL}}/1

###
POST {{apiURL}}
Content-Type: application/json

{  
    "author_id": 1,
    "text": "Köp bröd!" 
}

###
PUT {{apiURL}}/1
Content-Type: application/json

{ "text": "köp bröd"}

###
DELETE {{apiURL}}/6
