@apiURL = http://localhost:8080/notes

GET {{apiURL}}

###

POST {{apiURL}}
Content-Type: application/json

{  
    "author_id": 1,
    "text": "Köp bröd!"  
}

###

PUT {{apiURL}}/1
Content-Type: application/json

{
    "text": "Köp mjölk"
}

###

DELETE {{apiURL}}/5
